[phases.setup]
nixPkgs = ["python311", "nodejs_20", "ffmpeg", "wget", "curl"]

[phases.install]
cmds = [
    "npm install --production",
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -U --pre yt-dlp curl-cffi"
]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && npm start"
