[providers]
  node = {}

[phases.setup]
  nixPkgs = ["...", "ffmpeg", "python3"]

[phases.install_ytdlp]
  cmds = ["wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O yt-dlp", "chmod a+rx yt-dlp"]

[phases.install]
  cmds = ["npm install"]

[start]
  cmd = "node server/index.js"
